version: '3.9'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql      
    networks:
      - kcnet
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "ExampleOrg"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
      - "636:636"
    networks:
      - kcnet

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - kcnet

  # ldap:
  #   image: rroemhild/test-openldap
  #   container_name: ldap
  #   environment:
  #     LDAP_ORGANIZATION: TESTORG
  #     LDAP_DOMAIN: test.org
  #     LDAP_ADMIN_PASSWORD: admin
  #   ports:
  #     - "389:389"
  #     - "636:636"
  #   networks:
  #     - kcnet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    # if using dockerfile then build:
    build: .
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: conf/my-keystore.jks
      KC_HTTPS_KEY_STORE_PASSWORD: changeit
      KC_HTTPS_KEY_STORE_TYPE: JKS
      KC_HTTPS_PORT: 8443 
      # Add LDAP truststore to JVM
      JAVA_OPTS_APPEND: >-
        -Djavax.net.ssl.trustStore=/opt/keycloak/conf/ldap-truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
        -Djavax.net.ssl.trustStoreType=JKS          
    ports:
      - "8080:8080"
      - "8443:8443"    # HTTPS
    depends_on:
      - keycloak-db
      - openldap
    networks:
      - kcnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
networks:
  kcnet:
    driver: bridge