replicaCount: 5

auth:
  adminUser: admin
  adminPassword: admin

proxy: edge
httpRelativePath: /

tls:
  enabled: true
  existingSecret: keycloak-tls

cache:
  enabled: true
  stack: kubernetes

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 8443

extraEnvVars:
  - name: KC_DB
    value: "postgres"
  - name: KC_DB_URL
    value: "jdbc:postgresql://remote-postgres.example.com:5432/keycloak"
  - name: KC_DB_USERNAME
    value: "esskeycloakuser"
  - name: KC_DB_PASSWORD
    value: ""
  - name: KC_CACHE
    value: "ispn"
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: JAVA_OPTS_APPEND
    value: "-Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local"
  - name: KC_HOSTNAME_STRICT
    value: "false"

persistence:
  enabled: false   # since DB is external, no local PVC needed

externalDatabase:
  enabled: true
  existingSecret: ""   # not using chart secret; relying on extraEnvVars
  host: remote-postgres.example.com
  port: 5432
  user: keycloakuser
  password: keycloak
  database: keycloak

podAntiAffinityPreset: hard
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: keycloak

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.example.com
  tls: true
  extraTls:
    - hosts:
        - keycloak.example.com
      secretName: keycloak-tls
### Auto-scaler  params
application:
  name: my-app
  tag: v1.0.0

hpa:
  # General HPA config
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75   # scale when avg CPU > 75%

  # Behavior (scale up/down)
  stabilizationWindowSeconds: 60

  # Scaling policy type: "Pods" or "Percent"
  type: Percent

  # Scale down policies
  value90: 90     # scale down by 90% (if type=Percent)
  value1: 1       # scale down by 1 pod (if type=Pods)
  periodSeconds: 15
  selectPolicyMin: Min   # Min | Max | Disabled

  # Scale up policies
  value100: 100   # scale up by 100% (if type=Percent)
  selectPolicyMax: Max   # Min | Max | Disabled

